#!/bin/sh
# AIOS Bootstrap Script v0.1.0-p0
# Runs inside initramfs on first boot from USB.
# Detects hardware, selects model, creates persistence, launches orchestrator.

set -e

# === Color output ===
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[AIOS]${NC} $1"; }
warn() { echo -e "${YELLOW}[AIOS]${NC} $1"; }
err()  { echo -e "${RED}[AIOS]${NC} $1"; }

log "AIOS Bootstrap v0.1.0-p0 starting..."
log "========================================="

# === Stage 1: Hardware Detection ===
log "Detecting hardware..."

TOTAL_RAM=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo 2>/dev/null || echo "0")
CPU_CORES=$(nproc 2>/dev/null || echo "1")
CPU_MODEL=$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo 2>/dev/null | xargs || echo "unknown")

log "  RAM:        ${TOTAL_RAM} MB"
log "  CPU cores:  ${CPU_CORES}"
log "  CPU model:  ${CPU_MODEL}"

# === Stage 2: Model Selection ===
log "Selecting AI model based on available RAM..."

MODEL="gemma-3-1b-q4"       # Default: smallest fallback
REVIEWER_MODEL=""            # No reviewer by default
VALIDATOR_MODEL="ailo-152m-q4"  # Always include tiny validator

if [ "$TOTAL_RAM" -ge 4096 ]; then
    MODEL="deepseek-coder-1.3b-q4_k_m"
    log "  Selected PRIMARY: deepseek-coder-1.3b (4GB+ RAM)"
elif [ "$TOTAL_RAM" -ge 2048 ]; then
    MODEL="gemma-3-1b-q4"
    log "  Selected PRIMARY: gemma-3-1b (2-4GB RAM)"
else
    MODEL="ailo-152m-q4"
    VALIDATOR_MODEL=""
    warn "  Low RAM detected (< 2GB). Using ultra-light model. Expect slow responses."
fi

if [ "$TOTAL_RAM" -ge 8192 ]; then
    REVIEWER_MODEL="granite-3.2-2b-q4_k_m"
    log "  Selected REVIEWER: granite-3.2-2b (8GB+ RAM)"
fi

# === Stage 3: Find Persistence Disk ===
log "Locating persistence storage..."

# Try to find the USB device
USB_DEV=""
for dev in /dev/sd?; do
    if [ -b "$dev" ]; then
        SIZE=$(blockdev --getsize64 "$dev" 2>/dev/null || echo "0")
        # Look for 8GB+ devices (USB drives)
        if [ "$SIZE" -gt 7500000000 ] 2>/dev/null; then
            USB_DEV="$dev"
            log "  Found USB device: ${USB_DEV} (${SIZE} bytes)"
            break
        fi
    fi
done

if [ -z "$USB_DEV" ]; then
    # Fallback: use the first available disk
    USB_DEV=$(lsblk -ndo NAME | head -1)
    USB_DEV="/dev/${USB_DEV}"
    warn "  Could not auto-detect USB. Using: ${USB_DEV}"
fi

# === Stage 4: Create Persistence Partition ===
PERSIST_PART="${USB_DEV}2"
PERSIST_MOUNT="/mnt/persist"

log "Creating persistence partition on ${PERSIST_PART}..."

# WARNING: This will create a new partition. In production, check for existing first.
if [ ! -b "$PERSIST_PART" ]; then
    log "  Partitioning ${USB_DEV}..."
    echo -e "n\np\n2\n\n+6G\nw" | fdisk "$USB_DEV" > /dev/null 2>&1 || true
    sleep 1
fi

if [ -b "$PERSIST_PART" ]; then
    log "  Formatting ${PERSIST_PART} as ext4..."
    mkfs.ext4 -F "$PERSIST_PART" > /dev/null 2>&1 || warn "  Format may have failed (partition already formatted?)"
else
    err "  Failed to create persistence partition. Cannot continue."
    exit 1
fi

# === Stage 5: Mount Persistence ===
log "Mounting persistence at ${PERSIST_MOUNT}..."
mkdir -p "$PERSIST_MOUNT"
mount "$PERSIST_PART" "$PERSIST_MOUNT" || {
    err "  Failed to mount persistence partition."
    exit 1
}

# === Stage 6: Extract Bootstrap Tarball ===
BOOTSTRAP_TAR="/aios-bootstrap.tar.gz"

if [ -f "$BOOTSTRAP_TAR" ]; then
    log "Extracting AIOS bootstrap to persistence..."
    tar -xzf "$BOOTSTRAP_TAR" -C "$PERSIST_MOUNT" || {
        err "  Failed to extract bootstrap. USB image may be corrupted."
        exit 1
    }
else
    err "  Bootstrap tarball not found at ${BOOTSTRAP_TAR}."
    err "  The USB image is incomplete. Please reflash."
    exit 1
fi

# === Stage 7: Write Runtime Config ===
CONFIG_FILE="${PERSIST_MOUNT}/etc/aios.conf"
mkdir -p "$(dirname "$CONFIG_FILE")"

cat > "$CONFIG_FILE" << EOF
# AIOS Runtime Configuration — auto-generated by first_boot.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

HARDWARE_RAM_MB=${TOTAL_RAM}
HARDWARE_CPU_CORES=${CPU_CORES}
HARDWARE_CPU_MODEL="${CPU_MODEL}"

MODEL_PRIMARY=${MODEL}
MODEL_REVIEWER=${REVIEWER_MODEL}
MODEL_VALIDATOR=${VALIDATOR_MODEL}

BOOTSTRAP_VERSION=0.1.0-p0
FIRST_BOOT_COMPLETE=true
EOF

log "Runtime config written to ${CONFIG_FILE}"

# === Stage 8: Launch Orchestrator ===
log "========================================="
log "Bootstrap complete. Launching AIOS orchestrator..."
log ""

# Switch to persistence and launch
exec chroot "$PERSIST_MOUNT" /aios/bin/launch.sh || {
    err "Failed to launch orchestrator."
    err "Dropping to emergency shell..."
    exec /bin/sh
}
