#!/usr/bin/env python3
"""
AIOS Orchestrator — v0.1.0-p0 (Skeleton)
The central brain of AIOS. Loads models, manages agents, dispatches tasks.
"""
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

# === Configuration ===
AIOS_ROOT = Path(os.environ.get("AIOS_ROOT", "/mnt/persist/aios"))
MODELS_DIR = Path(os.environ.get("AIOS_MODELS", "/mnt/persist/models"))
CONFIG_FILE = Path("/etc/aios.conf")


def load_config() -> dict:
    """Load runtime configuration generated by first_boot.sh."""
    config = {}
    if CONFIG_FILE.exists():
        for line in CONFIG_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                config[key.strip()] = val.strip().strip('"')
    return config


class LlamaCPP:
    """Minimal llama.cpp wrapper for inference."""

    def __init__(self, model_path: str, n_ctx: int = 2048):
        self.model_path = model_path
        self.n_ctx = n_ctx
        self.process: Optional[subprocess.Popen] = None

    def load(self) -> bool:
        """Load the model via llama-cli."""
        llama_cli = os.path.join(AIOS_ROOT, "runtime", "llama.cpp", "llama-cli")
        if not os.path.exists(llama_cli):
            print(f"[ERROR] llama-cli not found at {llama_cli}")
            return False

        # In production, use llama.cpp's C API via ctypes or the Python bindings.
        # For POC, we spawn llama-cli in interactive mode.
        print(f"[LLM] Loading model: {self.model_path}")
        print(f"[LLM] Context window: {self.n_ctx} tokens")
        return True

    def generate(self, prompt: str, max_tokens: int = 512) -> str:
        """Generate a response. POC: subprocess call to llama-cli."""
        llama_cli = os.path.join(AIOS_ROOT, "runtime", "llama.cpp", "llama-cli")
        try:
            result = subprocess.run(
                [llama_cli, "-m", self.model_path, "-p", prompt,
                 "-n", str(max_tokens), "--ctx-size", str(self.n_ctx),
                 "--temp", "0.7", "--no-display-prompt"],
                capture_output=True, text=True, timeout=120
            )
            return result.stdout.strip()
        except subprocess.TimeoutExpired:
            return "[ERROR] Model inference timed out"
        except FileNotFoundError:
            return "[ERROR] llama-cli not found"


class Agent:
    """Base agent wrapping an LLM instance."""

    def __init__(self, name: str, model: LlamaCPP, role: str):
        self.name = name
        self.model = model
        self.role = role

    def generate(self, prompt: str) -> str:
        return self.model.generate(prompt)


class Gatekeeper:
    """Safety gatekeeper. AI proposes, gatekeeper evaluates."""

    SAFE = {"read", "list", "status", "cat", "ls", "find", "git log", "git status"}
    DANGEROUS = {"write", "install", "build", "make", "git clone", "git push", "apt", "apk"}
    DESTRUCTIVE = {"delete", "format", "rm", "dd", "mkfs", "fdisk"}

    @classmethod
    def evaluate(cls, command: str) -> tuple[str, str]:
        """Returns (risk_level, reason)."""
        cmd_lower = command.lower()

        # Protected paths
        for path in ["/boot", "/sys/kernel", "/proc/sys"]:
            if path in command:
                return ("destructive", f"Attempts to modify protected path: {path}")

        # Deletion commands
        for pattern in ["rm -rf /", "dd if=", "mkfs.", ":(){ :|:& };:"]:
            if pattern in command:
                return ("destructive", f"Matches destructive pattern: {pattern}")

        # Check against known sets
        first_word = command.split()[0] if command.split() else ""
        if first_word in cls.DESTRUCTIVE or any(d in cmd_lower for d in ["format", "fdisk", "dd if"]):
            return ("destructive", f"Command classified as destructive: {first_word}")
        if first_word in cls.DANGEROUS or any(d in cmd_lower for d in ["install", "build", "write"]):
            return ("dangerous", f"Command may modify system state: {first_word}")
        if first_word in cls.SAFE:
            return ("safe", "Read-only or status operation")

        return ("dangerous", "Unknown command — treating as potentially dangerous")


class Orchestrator:
    """Main orchestrator: loads agents, manages task queue, runs consensus."""

    def __init__(self, config: dict):
        self.config = config
        self.agents: dict[str, Agent] = {}
        self.gatekeeper = Gatekeeper()
        self.task_queue: list = []

    def initialize(self) -> bool:
        """Initialize all agents based on hardware config."""
        print("[AIOS] Initializing orchestrator...")
        print(f"[AIOS] Hardware: {self.config.get('HARDWARE_CPU_CORES', '?')} cores, "
              f"{self.config.get('HARDWARE_RAM_MB', '?')} MB RAM")

        # Load primary model
        primary_model_name = self.config.get("MODEL_PRIMARY", "gemma-3-1b-it-Q4_K_M")
        primary_path = MODELS_DIR / f"{primary_model_name}.gguf"

        if primary_path.exists():
            llm = LlamaCPP(str(primary_path))
            if llm.load():
                self.agents["primary"] = Agent("primary", llm, "code_generator")
                print(f"[AIOS] Primary agent loaded: {primary_model_name}")
        else:
            print(f"[ERROR] Primary model not found: {primary_path}")
            return False

        # Load reviewer model (if available)
        reviewer_model_name = self.config.get("MODEL_REVIEWER", "")
        if reviewer_model_name:
            reviewer_path = MODELS_DIR / f"{reviewer_model_name}.gguf"
            if reviewer_path.exists():
                llm = LlamaCPP(str(reviewer_path), n_ctx=1024)
                if llm.load():
                    self.agents["reviewer"] = Agent("reviewer", llm, "code_reviewer")
                    print(f"[AIOS] Reviewer agent loaded: {reviewer_model_name}")

        # Load validator model
        validator_model_name = self.config.get("MODEL_VALIDATOR", "")
        if validator_model_name:
            validator_path = MODELS_DIR / f"{validator_model_name}.gguf"
            if validator_path.exists():
                llm = LlamaCPP(str(validator_path), n_ctx=512)
                if llm.load():
                    self.agents["validator"] = Agent("validator", llm, "syntax_checker")
                    print(f"[AIOS] Validator agent loaded: {validator_model_name}")

        print(f"[AIOS] {len(self.agents)} agent(s) ready.")
        return True

    def run_console(self):
        """Simple console loop for Phase 0."""
        print()
        print("=" * 60)
        print("  AIOS — AI-Driven Operating System Kernel")
        print(f"  Agents active: {', '.join(self.agents.keys())}")
        print("  Type 'help' for commands, 'exit' to quit")
        print("=" * 60)
        print()

        while True:
            try:
                user_input = input("[AIOS] > ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\n[AIOS] Shutting down...")
                break

            if not user_input:
                continue

            if user_input.lower() in ("exit", "quit"):
                print("[AIOS] Goodbye.")
                break

            if user_input.lower() == "help":
                print("Commands: help, status, agents, exit")
                print("Any other input will be sent to the primary agent.")
                continue

            if user_input.lower() == "status":
                print(f"  Hardware: {self.config.get('HARDWARE_CPU_MODEL', 'unknown')}")
                print(f"  RAM: {self.config.get('HARDWARE_RAM_MB', '?')} MB")
                print(f"  Agents: {', '.join(self.agents.keys())}")
                continue

            if user_input.lower() == "agents":
                for name, agent in self.agents.items():
                    print(f"  {name}: {agent.role}")
                continue

            # Send to primary agent
            primary = self.agents.get("primary")
            if primary:
                print("[Primary thinking...]")
                response = primary.generate(user_input)

                # If reviewer is available, get a second opinion
                reviewer = self.agents.get("reviewer")
                if reviewer and len(user_input) > 20:
                    print("[Reviewer checking...]")
                    review_prompt = (
                        f"Review this AI response for errors, hallucinations, or security issues.\n\n"
                        f"USER REQUEST: {user_input}\n\n"
                        f"AI RESPONSE: {response}\n\n"
                        f"List any problems found (or say 'CLEAN' if none):"
                    )
                    review = reviewer.generate(review_prompt)
                    if "CLEAN" not in review.upper():
                        print(f"[Reviewer found issues] {review[:200]}...")

                print(f"\n{response}\n")
            else:
                print("[ERROR] No primary agent loaded.")


def main():
    config = load_config()
    orch = Orchestrator(config)

    if not orch.initialize():
        print("[FATAL] Orchestrator failed to initialize.")
        sys.exit(1)

    orch.run_console()


if __name__ == "__main__":
    main()
